/**
 * This code was generated by Builder.io.
 */
export interface NavigationItemProps {
  icon: string;
  label: string;
  href: string;
  isActive?: boolean;
}

export interface UserProfileProps {
  avatarUrl: string;
  settingsIconUrl: string;
}