/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { UserProfileProps } from './types';

export const UserProfile: React.FC<UserProfileProps> = ({ avatarUrl, settingsIconUrl }) => {
  return (
    <div className="flex flex-col">
      <img 
        loading="lazy" 
        src={avatarUrl} 
        alt="User avatar" 
        className="object-contain self-center w-8 aspect-square rounded-[80px]" 
      />
      <div className="flex flex-col justify-center items-center px-8 py-6 mt-2 w-full border-t border-cyan-900 max-md:px-5">
        <img 
          loading="lazy" 
          src={settingsIconUrl} 
          alt="Settings" 
          className="object-contain w-8 aspect-square rounded-[80px]" 
        />
      </div>
    </div>
  );
};