/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { InputFieldProps } from './types';

export const InputField: React.FC<InputFieldProps> = ({ label, value, type = "text" }) => {
  return (
    <div className="flex flex-col items-center w-full">
      <div className="flex flex-col w-full">
        <label htmlFor={label.toLowerCase()} className="text-sm leading-snug text-neutral-500">
          {label}
        </label>
        <input
          type={type}
          id={label.toLowerCase()}
          value={value}
          className="flex-1 shrink gap-2 self-stretch px-4 py-3.5 mt-1 w-full text-base font-medium leading-tight whitespace-nowrap rounded-lg border border-solid border-zinc-100 min-h-[48px] text-neutral-900"
          aria-label={label}
        />
      </div>
    </div>
  );
};